### ISSUE TITLE
can it have lables

### ISSUE THREAD

**Issue by prilcool** [benpickles/peity#106]
can it have  labels  i want to create x and y axis for  bar chart

**Comment by benpickles** [comment]
There's no official support for adding axes or labels (the charts are expected to be too small) but I imagine it could be achieved (though knowledge of undocumented Peity features and internals would likely be required 😬). It's not what you asked for but here's an example of adding tooltips to charts (taken from discussion in #71): https://jsbin.com/vufayan/edit?html,js,output
