### ISSUE TITLE
 jQuery version and Peity version always conflict

### ISSUE THREAD

**Issue by dningl** [benpickles/peity#108]
Its same like the jQuery version and Peity version always conflict in a vue project

**Comment by benpickles** [comment]
That doesn't sound good. I'm currently using it with jQuery 3.7.0 but Peity should work with any jQuery >=1.6.2.

If possible can you provide an example of it failing? Or console logs or a screenshot?

**Comment by dningl** [comment]
> 



> That doesn't sound good. I'm currently using it with jQuery 3.7.0 but Peity should work with any jQuery >=1.6.2.
> 
> If possible can you provide an example of it failing? Or console logs or a screenshot?



> 
I changed the jQuery version to 3.0 has solved the problem, thanks for the reply!
