### ISSUE TITLE
Update the color of the chart

### ISSUE THREAD

**Issue by julienduthoit** [benpickles/peity#30]
Hi,

I'm using your api to display some charts. Their values could be reloaded in Ajax, there is only a problem with the change function, I can't update the colors of the chart. Is there a way to do that? I can easily assign color dynamically at the chart generation but the update function doesn't seems to use the same information.

Thanks for your help

**Comment by highvoltag3** [comment]
+1 I have the same problem as @kzrdt actually your own example seems to have the issue
http://g.recordit.co/oGyV2GVooK.gif
