### ISSUE TITLE
Request: Keep nuget repository uptodate

### ISSUE THREAD

**Issue by AndrewMarshall1980** [benpickles/peity#62]
There is an existing NUGET package that is two major versions out of date.  Can I request that the NUGET package is maintained in line with the github release.

Thanks.  Andy.

**Comment by benpickles** [comment]
I've never heard of NuGet and it's unlikely I'd use it, it looks like the package is owned by [codedemon](https://www.nuget.org/profiles/codedemon) so they'll have to keep it up-to-date.

FYI Peity is now available on NPM: https://www.npmjs.com/package/peity
