### ISSUE TITLE
Bar chart width

### ISSUE THREAD

**Issue by AsMoh** [benpickles/peity#74]
Hi, 

I have included the peity  library, and inside a div I added this line
<span class="bar">5,3,9,6,5,9,7,3,5,2</span>.
And I added this line to my script file.
$(".bar").peity("bar")

However, the bar chart is displayed as a line as shown in the following image.

![peity](https://cloud.githubusercontent.com/assets/10277729/9154524/7603af9e-3ea4-11e5-8fdc-a9ae44b248ee.jpg)

![peity2](https://cloud.githubusercontent.com/assets/10277729/9154547/198bd910-3ea6-11e5-8db2-1647e291e18c.jpg)

Can you guide me to solve this problem, please? I tried to increase the width and the height of class bar , but it did not work.

Thank you in advance.

**Comment by benpickles** [comment]
My guess is that there's a later call to create a Peity line chart that's overwriting the bar chart call. Perhaps if you comment out all other calls to Peity you may be able to see a working bar chart and track down the offending code.

**Comment by AsMoh** [comment]
Ohh .. You are right .. Thank you so much.
