### ISSUE TITLE
change() doesn't update colors...

### ISSUE THREAD

**Issue by highvoltag3** [benpickles/peity#78]
I'm having the same problem as @kzrd which reported on #30 and I saw your example which actually seems to show that it in fact doesn't work.. since the bars are always blue.
http://g.recordit.co/oGyV2GVooK.gif

**Comment by benpickles** [comment]
Ah, I'm not sure of your issue but the reason the example in #30 wasn't working is due to a change in the API between versions 1 and 2. Here's the updated example: http://jsfiddle.net/benpickles/KFbz8/

Let me know if this doesn't fix your issue.

**Comment by highvoltag3** [comment]
@benpickles your completely right, thanks for the updated example and tho I see it working I was just wondering what exactly was the change I don't seem to see it (doesn't seem that obvious).

Thanks a ton! for the great work.

**Comment by benpickles** [comment]
Thanks, the only change is renaming the `colour` option to `fill`.
