### ISSUE TITLE
Possible to add text inside of donut?

### ISSUE THREAD

**Issue by liuwenchao** [benpickles/peity#79]
Is there an easy way to add text inside of donut? like:

```
<span class="donut" data-peity="{'text': 'Shares per stakeholder'}">1,2,3,2,2</span>
```

**Comment by benpickles** [comment]
If you're looking for a standard browser tooltip it looks like this is possible by using an outer element like so: http://jsbin.com/dukavi/edit?html,js,output

Let me know if this isn't what you were thinking of.

**Comment by liuwenchao** [comment]
@benpickles I'm looking for a text element positioned inside of a donut circle, not a tooltip.

http://jsbin.com/vopenibuqu/edit?html,js,output

**Comment by benpickles** [comment]
I don't know about "easy" (!) but Peity does expose a few things to you so you can decorate a chart utilising some of Peity's internal helper functions. I've updated the example to demonstrate: http://jsbin.com/dukavi/edit?js,output

**Comment by liuwenchao** [comment]
:+1:
