### ISSUE TITLE
Smooth animate pie chart on update

### ISSUE THREAD

**Issue by jeffceriello** [benpickles/peity#88]
Hi there,

Is it possible to smoothly animate the lines of the pie chart instead of a jump?

**Comment by benpickles** [comment]
The short answer is "no"! Happy to discuss further though :)

**Comment by jeffceriello** [comment]
:) The idea would be to have a "simple" pie animation like on this codepen

http://codepen.io/FlyersPh9/pen/Bytpg

If you click on Q1, Q2, .... you should see the pie animate.

Would that be possible within Peity? If so, could you please point me to the right direction?

Here is a quick jsfiddle that shows a pie chart made with Peity and an Update button that updates the chart

https://jsfiddle.net/nrmsfyo8/
