### ISSUE TITLE
Charting fractional values

### ISSUE THREAD

**Issue by rlightner** [benpickles/peity#91]
I'm trying to use this for charting Specific Gravity for beer brewing.

I'd like to see the following values in a line chart or even bar, but for some reason its just showing a flat-ish line.

1.053,1.052,1.045,1.032,1.023,1.017,1.014,1.010,1.008

![image](https://cloud.githubusercontent.com/assets/354640/22429679/3dc0b7f6-e6c0-11e6-8631-b9c221351de4.png)

Thoughts?

**Comment by benpickles** [comment]
Peity defaults to a minimum value of zero but you can pass in your own minimum like so:

```js
$('span').peity('line', {
  min: 1,
})
```

Here's an example: https://jsbin.com/godoni/edit?html,js,output
